### ISSUE TITLE
Function `update_structure_matrix` undefined

### ISSUE THREAD

**Issue by simon-forb** [ArthurLeoM/FGWMixup#1]
Hi,

The function `update_structure_matrix` the the module `FGW_barycenter.py` in line 174 is undefined. No reference can be found in the whole repo.

https://github.com/ArthurLeoM/FGWMixup/blob/e645ce9045555bce6c211a3118e7204f20621703/src/FGW_barycenter.py#L174

**Comment by ArthurLeoM** [comment]
Hi. This function is defined in pot lib (ot.gromov), ver 0.8.2. In their latest version 0.9.3, this function has been renamed as update_kl_loss and update_square_loss. You can also refer to their new solver version and slightly modify this code for your own purpose.
