### ISSUE TITLE
Computation of Degree as Node Weights

### ISSUE THREAD

**Issue by simon-forb** [ArthurLeoM/FGWMixup#2]
Hi,

I do not understand why the parameters `a` and `b` are used in the computation of the normalized degrees. Especially when using the given defaults for these parameters, in particular `b = 0`, one obtains the same values for all nodes and the degree option is equivalent to the uniform option.

I'd be very grateful if you could shed some light on this.

https://github.com/ArthurLeoM/FGWMixup/blob/7c8faec41b05e89947d7938f73be6cc10564417e/src/gromov_mixup.py#L100

**Comment by ArthurLeoM** [comment]
We are actually using the uniform distribution in our experiments. (See our shell script ```run_gmixup.sh```, ```--measure=uniform```) It is also okay to adjust the hyperparams (```a, b```) if you attempt to use the degree distribution. 
It is correct that a=b=0 is a setting equivalent to the uniform distribution, where we aim to make users reproduce the results even when they set the ```measure``` argument to ```degree```.
